# Generated by Django 6.0.3 on 2026-03-19 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slno', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=50)),
                ('property_class', models.CharField(max_length=50)),
                ('room_category', models.CharField(max_length=50)),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('has_multiple_property', models.BooleanField(default=False)),
                ('number_of_properties', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_committed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=255)),
                ('primary_contact_person', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=32)),
                ('primary_person_position', models.CharField(blank=True, max_length=100, null=True)),
                ('executive_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_visit_date', models.DateField()),
                ('first_visit_status', models.CharField(max_length=100)),
                ('committed_proposed_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True)),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('rescheduled_comment', models.TextField(blank=True, null=True)),
                ('second_visit_executive', models.CharField(blank=True, max_length=100, null=True)),
                ('second_visit_date', models.DateField(blank=True, null=True)),
                ('second_visit_status', models.CharField(blank=True, max_length=100, null=True)),
                ('second_visit_comments', models.TextField(blank=True, null=True)),
                ('currently_assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=100, null=True)),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plan_start_date', models.DateField()),
                ('plan_expiry_date', models.DateField()),
                ('location_link', models.URLField()),
                ('current_pms', models.CharField(max_length=100)),
                ('connected_ota_platforms', models.JSONField(default=list)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slno'],
            },
        ),
    ]
