# Generated by Django 6.0.3 on 2026-03-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueFeature',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=64)),
                ('release_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='Operations', max_length=64)),
                ('status', models.CharField(choices=[('New', 'New'), ('Updated', 'Updated'), ('Stable', 'Stable')], default='Stable', max_length=20)),
                ('icon_key', models.CharField(default='Layers', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-release_date', 'name'],
            },
        ),
    ]
