# Generated by Django 6.0.3 on 2026-03-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeFairVenue',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TravelAgent',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slno', models.PositiveIntegerField()),
                ('agent_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('trial_status', models.BooleanField(default=False)),
                ('trial_remaining_days', models.PositiveIntegerField(default=0)),
                ('plan_start_date', models.DateField()),
                ('plan_end_date', models.DateField()),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contract_type', models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=32)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['slno'],
            },
        ),
        migrations.CreateModel(
            name='TradeFairProperty',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Interested', 'Interested'), ('Requested Demo', 'Requested Demo'), ('Connected', 'Connected'), ('Closed', 'Closed'), ('Payment Done', 'Payment Done')], max_length=32)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='partners.tradefairvenue')),
            ],
            options={
                'ordering': ['property_name'],
            },
        ),
        migrations.CreateModel(
            name='TradeFairAgent',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('is_dmc', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Interested', 'Interested'), ('Requested Demo', 'Requested Demo'), ('Connected', 'Connected'), ('Closed', 'Closed'), ('Payment Done', 'Payment Done')], max_length=32)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='partners.tradefairvenue')),
            ],
            options={
                'ordering': ['agent_name'],
            },
        ),
    ]
