from __future__ import annotations

from decimal import Decimal

from .models import SalesRecord


def run() -> None:
  # Sales records seed (attendance is only created via real punch-in/out API)
  if SalesRecord.objects.exists():
    return

  from apps.properties.models import Property

  props = list(Property.objects.filter(is_deleted=False)[:7])
  defaults = [
    {
      "id": "s1",
      "slno": 1,
      "property_name": "Ocean Breeze Resort",
      "number_of_rooms": 45,
      "email": "info@oceanbreeze.com",
      "primary_contact_person": "Rajesh Kumar",
      "designation": "Manager",
      "proposed_price": Decimal("150000"),
      "plan_type": SalesRecord.PLAN_1_YEAR,
      "status": SalesRecord.STATUS_CLOSED,
      "comments": "Premium client. Full OTA integration done.",
      "demo_provided": True,
      "trial_provided": True,
      "installed": True,
      "executive": "Anil Menon",
      "state": "Kerala",
      "district": "Kozhikode",
      "location": "Calicut Beach",
      "location_link": "https://maps.google.com",
      "is_live": True,
      "visit_history": [
        {"date": "2026-03-01", "time": "10:00 AM", "status": "Interested", "comment": "Initial discussion."},
        {"date": "2026-03-05", "time": "02:00 PM", "status": "Requested Demo", "comment": "Full demo given."},
        {"date": "2026-03-10", "time": "11:00 AM", "status": "Closed", "comment": "Contract signed."},
      ],
    },
    {
      "id": "s2",
      "slno": 2,
      "property_name": "Kappad Heritage Inn",
      "number_of_rooms": 18,
      "email": "book@kappadinn.in",
      "primary_contact_person": "Priya Nair",
      "designation": "Owner",
      "proposed_price": Decimal("85000"),
      "plan_type": SalesRecord.PLAN_1_YEAR,
      "status": SalesRecord.STATUS_CLOSED,
      "comments": "Smooth onboarding.",
      "demo_provided": True,
      "trial_provided": False,
      "installed": True,
      "executive": "Deepa S",
      "state": "Kerala",
      "district": "Kozhikode",
      "location": "Kappad",
      "location_link": "https://maps.google.com",
      "is_live": True,
      "visit_history": [
        {"date": "2026-02-15", "time": "03:30 PM", "status": "Interested", "comment": "Met owner Priya."},
        {"date": "2026-02-20", "time": "10:00 AM", "status": "Closed", "comment": "Closing call successful."},
      ],
    },
    {
      "id": "s3",
      "slno": 3,
      "property_name": "Marine Drive Suites",
      "number_of_rooms": 28,
      "email": "info@marinedrivesuites.com",
      "primary_contact_person": "Meera Krishnan",
      "designation": "Front Office",
      "proposed_price": Decimal("120000"),
      "plan_type": SalesRecord.PLAN_1_YEAR,
      "status": SalesRecord.STATUS_INTERESTED,
      "comments": "Evaluating competitors.",
      "demo_provided": True,
      "trial_provided": True,
      "installed": False,
      "executive": "Rajan K",
      "state": "Kerala",
      "district": "Ernakulam",
      "location": "Marine Drive",
      "location_link": "",
      "is_live": False,
      "visit_history": [{"date": "2026-03-12", "time": "04:30 PM", "status": "Interested", "comment": "Checking trial."}],
    },
    {
      "id": "s4",
      "slno": 4,
      "property_name": "Whitefield Business Lodging",
      "number_of_rooms": 16,
      "email": "book@wflodging.in",
      "primary_contact_person": "Kavitha M",
      "designation": "HR",
      "proposed_price": Decimal("55000"),
      "plan_type": SalesRecord.PLAN_6_MONTH,
      "status": SalesRecord.STATUS_RESCHEDULED,
      "comments": "Budget constraints.",
      "demo_provided": True,
      "trial_provided": False,
      "installed": False,
      "executive": "Vishal P",
      "state": "Karnataka",
      "district": "Bangalore Urban",
      "location": "Whitefield",
      "location_link": "",
      "is_live": False,
      "visit_history": [{"date": "2026-03-01", "time": "11:00 AM", "status": "Interested", "comment": "HR requested budget."}],
    },
    {
      "id": "s5",
      "slno": 5,
      "property_name": "Palolem Beach Resort",
      "number_of_rooms": 32,
      "email": "info@palolemresort.com",
      "primary_contact_person": "Carlos M",
      "designation": "Owner",
      "proposed_price": Decimal("130000"),
      "plan_type": SalesRecord.PLAN_1_YEAR,
      "status": SalesRecord.STATUS_NOT_INTERESTED,
      "comments": "Using competitor.",
      "demo_provided": True,
      "trial_provided": False,
      "installed": False,
      "executive": "Anil Menon",
      "state": "Goa",
      "district": "South Goa",
      "location": "Palolem",
      "location_link": "",
      "is_live": False,
      "visit_history": [{"date": "2026-03-05", "time": "10:00 AM", "status": "Not Interested", "comment": "Happy with current PMS."}],
    },
    {
      "id": "s6",
      "slno": 6,
      "property_name": "Fort Kochi Grand Hotel",
      "number_of_rooms": 72,
      "email": "reservations@fkgrand.com",
      "primary_contact_person": "Anitha George",
      "designation": "Manager",
      "proposed_price": Decimal("250000"),
      "plan_type": SalesRecord.PLAN_1_YEAR,
      "status": SalesRecord.STATUS_CLOSED,
      "comments": "Enterprise client.",
      "demo_provided": True,
      "trial_provided": True,
      "installed": True,
      "executive": "Anil Menon",
      "state": "Kerala",
      "district": "Ernakulam",
      "location": "Fort Kochi",
      "location_link": "",
      "is_live": True,
      "visit_history": [
        {"date": "2026-02-10", "time": "09:00 AM", "status": "Interested", "comment": "Large scale."},
        {"date": "2026-02-25", "time": "03:00 PM", "status": "Closed", "comment": "Approved by board."},
      ],
    },
    {
      "id": "s7",
      "slno": 7,
      "property_name": "Baga Beachfront Hotel",
      "number_of_rooms": 25,
      "email": "info@bagabeachfront.com",
      "primary_contact_person": "Rahul D'Souza",
      "designation": "Owner",
      "proposed_price": Decimal("110000"),
      "plan_type": SalesRecord.PLAN_1_YEAR,
      "status": SalesRecord.STATUS_INSTALLATION_PENDING,
      "comments": "Payment done. Awaiting setup.",
      "demo_provided": True,
      "trial_provided": True,
      "installed": False,
      "executive": "Anil Menon",
      "state": "Goa",
      "district": "North Goa",
      "location": "Baga",
      "location_link": "",
      "is_live": False,
      "visit_history": [{"date": "2026-03-14", "time": "02:00 PM", "status": "Installation Pending", "comment": "Staff training scheduled."}],
    },
  ]
  for d in defaults:
    prop = None
    for p in props:
      if p.name == d["property_name"]:
        prop = p
        break
    SalesRecord.objects.create(property=prop, **d)
