# Generated by Django 6.0.3 on 2026-03-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slno', models.PositiveIntegerField()),
                ('property_name', models.CharField(max_length=255)),
                ('number_of_rooms', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_person', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan_type', models.CharField(choices=[('6 Month', '6 Month'), ('1 Year', '1 Year')], max_length=20)),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Installation Pending', 'Installation Pending'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Rescheduled', 'Rescheduled'), ('Under Maintenance', 'Under Maintenance')], max_length=32)),
                ('comments', models.TextField(blank=True)),
                ('demo_provided', models.BooleanField(default=False)),
                ('trial_provided', models.BooleanField(default=False)),
                ('installed', models.BooleanField(default=False)),
                ('executive', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('location_link', models.URLField(blank=True)),
                ('is_live', models.BooleanField(default=False)),
                ('visit_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='properties.property')),
            ],
            options={
                'ordering': ['slno'],
            },
        ),
    ]
