# Generated by Django 6.0.3 on 2026-03-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesattendance_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesattendance',
            name='check_in_selfie',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salesattendance',
            name='check_out_selfie',
            field=models.TextField(blank=True),
        ),
    ]
